#!/usr/bin/env bash

source /usr/local/rvm/environments/ruby-2.0.0-p353
cd /root/viewer/hERmes_viewer
bundle install
ruby -v
which ruby
echo "start duration test"
ruby cloud_feeds.rb -a atom_hopper -s staging -t duration -c start -l 720 -d "This is the weekly cloud feeds test" -n "Load test against cloud feeds" -r jmeter -e 10.23.244.38 --test-agent-slaves 10.23.244.38,10.23.246.100,10.23.246.101 --protocol https --port 443 --target-server atom.staging.ord1.uk.ci.rackspace.net
echo "stop duration test"
ruby cloud_feeds.rb -a atom_hopper -s staging -t duration -c stop -l 720 -d "This is the weekly cloud feeds test" -n "Load test against cloud feeds" -r jmeter -e 10.23.244.38 --test-agent-slaves 10.23.244.38,10.23.246.100,10.23.246.101 --protocol https --port 443 --target-server atom.staging.ord1.uk.ci.rackspace.net
echo "finished duration test."
