#!/usr/bin/env bash

source /usr/local/rvm/environments/ruby-2.0.0-p353
cd /root/viewer/hERmes_viewer
bundle install
ruby -v
which ruby
echo "start load test"
ruby cloud_feeds.rb -a atom_hopper -s staging -t load -c start -l 120 -d "This is the nightly cloud feeds test" -n "Load test against cloud feeds" -r jmeter -e 10.23.80.100
echo "stop load test"
ruby cloud_feeds.rb -a atom_hopper -s staging -t load -c stop -l 120 -d "This is the nightly cloud feeds test" -n "Load test against cloud feeds" -r jmeter -e 10.23.80.100
echo "finished load test."
echo "start stress test"
ruby cloud_feeds.rb -a atom_hopper -s staging -t stress -c start -l 180 -d "This is the nightly cloud feeds test" -n "Stress test against cloud feeds" -r jmeter -e 10.23.80.100
echo "stop stress test"
ruby cloud_feeds.rb -a atom_hopper -s staging -t stress -c stop -l 180 -d "This is the nightly cloud feeds test" -n "Stress test against cloud feeds" -r jmeter -e 10.23.80.100
echo "finished stress test."
