---
application:
  name: Graphite Singular App
  description: 
  location: apps/graphite_singular_app/bootstrap.rb
  type: singular
  plugins: 
   - location: plugins/graphite_rest_plugin/plugin.rb
  sub_apps:
  - id: main
    name: Main
    description: main description
