---
application:
  name: File
  description: test
  location: apps/file_singular_app/bootstrap.rb
  type: singular
  plugins:
  - location: plugins/file_plugin/plugin.rb
  sub_apps:
  - id: main
    name: Main setup
    description: Main description.
  - id: main
    name: Main setup
    description: Main description.
