---
application:
  name: Atom
  description: open source ATOMPub server (using Apache Abdera and licensed under
    Apache License v2.0 with the source code available on GitHub) for accessing, processing
    and aggregating ATOM entries.
  location: apps/atom_hopper/bootstrap.rb
  type: singular
  plugins:
  - location: plugins/repose_jmx_plugin/plugin.rb
  - location: plugins/file_plugin/plugin.rb
  - location: plugins/graphite_rest_plugin/plugin.rb
  - location: plugins/newrelic_rest_plugin/plugin.rb
  sub_apps:
  - id: staging
    name: Staging environment
    description: Atom Hopper setup in Staging environment
  - id: staging
    name: Staging environment
    description: Atom Hopper setup in Staging environment
  - id: staging
    name: Staging environment
    description: Atom Hopper setup in Staging environment
