application:
  name: Overhead
  description: Overhead application.  Just an example of how to compare two tests in 1 container
  location: apps/overhead/bootstrap.rb
  type: comparison
  plugins:
   - location: plugins/sysstats_plugin/plugin.rb
   - location: plugins/repose_jmx_plugin/plugin.rb
  sub_apps:
   -
     id: main
     name: Main application
     description: This is the base configuration for Repose
