---
application:
  name: Rest Singular App
  description: 
  location: apps/rest_singular_app/bootstrap.rb
  type: singular
  plugins: 
   - location: plugins/generic_rest_plugin/plugin.rb
  sub_apps:
  - id: main
    name: main
    description: main application
